name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          username: Ahmedali3ff
          output: dist/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          username: Ahmedali3ff
          output: dist/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Stats
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
